name: mainjaml

on:
    workflow_dispatch:
        inputs:
            myVar:
                type: string
                required: true
                description: 'asd'
                default: 'yoooo'


jobs:
    dajob:
      uses: convictional/trigger-workflow-and-wait@v1.6.5
      with:
        owner: gomorg
        repo: PeakGit/mercury-chatapp-infra
        github_token: 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
        github_user: gomorg 
        workflow_file_name: deploy.yml
        ref: main
        wait_interval: 300
        client_payload: '{"environment": "dev", "frontendImageTag": "unchanged", backendImageTag: "unchanged", "helmChartVersion": "latest"}'
        propagate_failure: false
        trigger_workflow: true
        wait_workflow: true
