name: mainjaml

on:
    workflow_dispatch:
        inputs:
            myVar:
                type: string
                required: true
                description: 'asd'
                default: 'yoooo'


jobs:
    dajob:
      runs-on: self-hosted
      steps:
        - name: something
          run: |
            echo "something something"

        # - name: apitest            
        #   uses: convictional/trigger-workflow-and-wait@v1.6.5
        #   with:
        #     owner: PeakGit
        #     repo: mercury-chatapp-infra
        #     github_token: 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
        #     github_user: gomorg 
        #     workflow_file_name: deploy.yml
        #     ref: main
        #     wait_interval: 300
        #     client_payload: '{"environment": "dev", "frontendImageTag": "unchanged", "backendImageTag": "unchanged", "helmChartVersion": "latest"}'
        #     propagate_failure: false
        #     trigger_workflow: true
        #     wait_workflow: true

        # - name: Login via Azure CLI
        #   uses: azure/login@v1
        #   with:
        #     creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        # - name: Checkout repository
        #   uses: actions/checkout@v2
        
        # - name: clone supertokens
        #   uses: actions/checkout@v2
        #   with:
        #     repository: 'supertokens/supertokens-docker-postgresql'
        #     ref: 'master'
        #     path: 'supertokens'

        # - name: debug
        #   run: |
        #     tree && ls -l  && ls -ld supertokens && du -sh supertokens && ls -l supertokens && tree supertokens
